package com.paf.gestaooperacional;

import android.content.Context;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class CompatClient {
    private static final String ROOT="https://salmon-woodcock-375027.hostingersite.com/";
    private static final Pattern CSRF=Pattern.compile("name=[\"']csrf[\"'][^>]*value=[\"']([^\"']+)[\"']",Pattern.CASE_INSENSITIVE);
    private static final Pattern OPTION=Pattern.compile("<option([^>]*)value=[\"']?([0-9]+)[\"']?([^>]*)>(.*?)</option>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL);
    private CompatClient(){}

    public static boolean hasSession(Context ctx){OfflineDb db=OfflineDb.get(ctx);return !db.getSetting("web_cookie","").isEmpty()&&!db.getSetting("web_csrf","").isEmpty();}

    public static void login(Context ctx,String login,String password) throws Exception{
        OfflineDb db=OfflineDb.get(ctx);
        Response first=request(ctx,"GET","login.php",(byte[])null,null,false,null);
        String csrf=extractCsrf(first.body);if(csrf.isEmpty())throw new IllegalStateException("Não foi possível preparar a sessão do aplicativo.");
        Map<String,String> f=new LinkedHashMap<>();f.put("csrf",csrf);f.put("action","login");f.put("login",login);f.put("senha",password);
        Response r=request(ctx,"POST","action.php",form(f).getBytes(StandardCharsets.UTF_8),"application/x-www-form-urlencoded; charset=utf-8",false,null);
        String loc=r.location==null?"":r.location;if((r.code<300||r.code>=400)&&r.code!=200)throw new IllegalStateException("Não foi possível abrir a sessão de dados.");if(loc.contains("login.php")||loc.contains("erro="))throw new IllegalStateException("Usuário ou senha inválidos.");
        db.putSetting("web_csrf",csrf);
        Response verify=request(ctx,"GET","campo.php",(byte[])null,null,false,null);if(verify.code>=400||verify.body.contains("name=\"action\" value=\"login\""))throw new IllegalStateException("A sessão de dados não pôde ser confirmada.");
    }

    public static JSONObject bootstrap(Context ctx,int groupId) throws Exception{
        if(!hasSession(ctx))throw new IllegalStateException("Faça login novamente com internet para atualizar a base deste aparelho.");
        OfflineDb db=OfflineDb.get(ctx);String start=dateOffset(-365),end=dateOffset(365);
        JSONObject webgeo=getJson(ctx,"webgeo_dados.php?visao=grupo");JSONObject report=getJson(ctx,"relatorio_diario_dados.php?data_inicio="+start+"&data_fim="+end);JSONObject map=getJson(ctx,"mapa_dados.php?inicio="+start+"&fim="+end);JSONObject routes=getJson(ctx,"rotas_dados.php?inicio="+start+"&fim="+end);
        String programHtml=request(ctx,"GET","index.php?page=programacao_form",(byte[])null,null,false,null).body;String checklistHtml=request(ctx,"GET","checklist_veiculo.php",(byte[])null,null,false,null).body;

        JSONArray produtores=new JSONArray(),plantios=new JSONArray();Map<Integer,JSONObject> prodMap=new LinkedHashMap<>();JSONArray rows=webgeo.optJSONArray("rows");if(rows==null)rows=new JSONArray();
        for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(r==null)continue;int pid=r.optInt("produtor_id");if(pid>0&&!prodMap.containsKey(pid)){JSONObject p=new JSONObject();p.put("id",pid);p.put("nome",r.optString("produtor"));p.put("cpf",r.optString("cpf"));p.put("cod_fornecedor",r.optString("cod_fornecedor"));p.put("telefone",r.optString("telefone"));p.put("cidade",r.optString("cidade"));p.put("status_atual",r.optString("status"));prodMap.put(pid,p);}JSONObject pl=new JSONObject(r.toString());pl.put("id",r.optInt("plantio_id"));pl.put("produtor_id",pid);pl.put("comunidade_nome",r.optString("comunidade"));pl.put("tecnico_nome",r.optString("tecnico"));pl.put("polo_sigla",r.optString("polo"));plantios.put(pl);}for(JSONObject p:prodMap.values())produtores.put(p);

        JSONArray communities=webgeo.optJSONArray("communities");if(communities==null)communities=new JSONArray();JSONArray programas=new JSONArray();JSONArray rr=report.optJSONArray("rows");if(rr==null)rr=new JSONArray();
        for(int i=0;i<rr.length();i++){JSONObject r=rr.optJSONObject(i);if(r==null)continue;JSONObject p=new JSONObject(r.toString());p.put("tecnico_nome",r.optString("tecnico"));p.put("tecnico_matricula",r.optString("matricula"));p.put("comunidade_nome",r.optString("comunidade"));p.put("atividade_nome",r.optString("atividade"));p.put("polo_sigla",r.optString("polo"));p.put("placa",r.optString("placa"));programas.put(p);}
        JSONArray pontos=map.optJSONArray("points");if(pontos==null)pontos=new JSONArray();JSONArray equipe=map.optJSONArray("teams");if(equipe==null)equipe=new JSONArray();JSONArray sessoes=new JSONArray(),localizacoes=new JSONArray();JSONArray ra=routes.optJSONArray("routes");if(ra==null)ra=new JSONArray();
        for(int i=0;i<ra.length();i++){JSONObject item=ra.optJSONObject(i);if(item==null)continue;JSONObject se=item.optJSONObject("session");if(se!=null)sessoes.put(se);JSONArray pts=item.optJSONArray("points");if(pts==null)continue;int sid=se==null?0:se.optInt("id");for(int j=0;j<pts.length();j++){JSONObject p=pts.optJSONObject(j);if(p==null)continue;JSONObject q=new JSONObject(p.toString());q.put("sessao_id",sid);localizacoes.put(q);}}
        JSONArray atividades=parseSelect(programHtml,"atividade_id","nome"),polos=parseSelect(programHtml,"polo_id","nome"),veiculos=parseVehicles(programHtml),checkItems=parseChecklistItems(checklistHtml),aprov=new JSONArray();for(int i=0;i<programas.length();i++){JSONObject p=programas.optJSONObject(i);String st=p==null?"":p.optString("status").toUpperCase(Locale.ROOT);if(st.equals("PENDENTE")||st.equals("PENDENTE_APROVACAO")||st.equals("ENVIADO"))aprov.put(p);}
        JSONObject data=new JSONObject();data.put("polos",polos);data.put("comunidades",communities);data.put("atividades",atividades);data.put("veiculos",veiculos);data.put("checklist_veiculo_itens",checkItems);data.put("programacoes",programas);data.put("aprovacoes_programacoes",aprov);data.put("produtores",produtores);data.put("plantios",plantios);data.put("pontos",pontos);data.put("equipe",equipe);data.put("sessoes",sessoes);data.put("localizacoes",localizacoes);data.put("checklists_veiculo",new JSONArray());data.put("checklists_pendentes",new JSONArray());data.put("movimentacoes_veiculos",new JSONArray());
        JSONObject out=new JSONObject();out.put("ok",true);out.put("version","compatibilidade-web");out.put("server_time",new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(new Date()));out.put("group_id",groupId);out.put("user",json(db.getSetting("user_json","{}")));out.put("groups",array(db.getSetting("groups_json","[]")));out.put("data",data);out.put("modo_compatibilidade",true);return out;
    }

    public static JSONObject syncOperation(Context ctx,String type,JSONObject payload,String photosJson) throws Exception{
        if(!hasSession(ctx))throw new IllegalStateException("Faça login novamente com internet para sincronizar os dados.");if("programacao.create".equals(type))return syncProgram(ctx,payload);if("ponto.create".equals(type))return syncPoint(ctx,payload,photosJson);if("vehicle_checklist.create".equals(type))return syncChecklist(ctx,payload,photosJson);if("route.sync".equals(type))return syncRoute(ctx,payload);throw new IllegalStateException("Este registro precisa da atualização do servidor para ser sincronizado.");
    }

    private static JSONObject syncProgram(Context ctx,JSONObject p) throws Exception{Map<String,String> f=baseFields(ctx);f.put("action","save_program");f.put("modo","ENVIAR");put(f,"data_programada",p.optString("data_programada"));put(f,"hora_inicio",p.optString("hora_inicio"));put(f,"hora_fim",p.optString("hora_fim"));put(f,"atividade_id",n(p.optInt("atividade_id")));put(f,"comunidade_id",n(p.optInt("comunidade_id")));put(f,"polo_id",n(p.optInt("polo_id")));put(f,"veiculo_id",n(p.optInt("veiculo_id")));put(f,"observacao_tecnico",p.optString("observacao_tecnico",p.optString("observacao")));f.put("prioridade",p.optString("prioridade","NORMAL"));Response r=request(ctx,"POST","action.php",form(f).getBytes(StandardCharsets.UTF_8),"application/x-www-form-urlencoded; charset=utf-8",false,null);ensureRedirectOk(r,"programação");return new JSONObject().put("ok",true).put("mensagem","Programação enviada.");}
    private static JSONObject syncPoint(Context ctx,JSONObject p,String photosJson) throws Exception{Map<String,String> f=baseFields(ctx);put(f,"nome_produtor",p.optString("nome_produtor"));put(f,"cpf_produtor",p.optString("cpf_produtor"));put(f,"produtor_id",n(p.optInt("produtor_id")));put(f,"plantio_id",n(p.optInt("plantio_id")));put(f,"comunidade_id",n(p.optInt("comunidade_id")));put(f,"programacao_id",n(p.optInt("programacao_id")));put(f,"observacao",p.optString("observacao"));put(f,"latitude",String.valueOf(p.optDouble("latitude")));put(f,"longitude",String.valueOf(p.optDouble("longitude")));if(p.has("precisao_metros"))put(f,"precisao_metros",String.valueOf(p.optDouble("precisao_metros")));Response r=multipart(ctx,"ponto_salvar.php",f,photoFiles(photosJson,null));JSONObject j=parseJson(r.body);if(!j.optBoolean("ok",false))throw new IllegalStateException(j.optString("error","Falha ao enviar o ponto."));return j;}
    private static JSONObject syncChecklist(Context ctx,JSONObject p,String photosJson) throws Exception{Map<String,String> f=baseFields(ctx);put(f,"veiculo_id",n(p.optInt("veiculo_id")));put(f,"programacao_id",n(p.optInt("programacao_id")));put(f,"odometro_inicial_km",String.valueOf(p.optDouble("odometro_inicial_km",p.optDouble("odometro_km",0))));if(p.has("latitude"))put(f,"latitude",String.valueOf(p.optDouble("latitude")));if(p.has("longitude"))put(f,"longitude",String.valueOf(p.optDouble("longitude")));String obs=p.optString("observacao");StringBuilder extra=new StringBuilder(obs==null?"":obs);append(extra,"Tipo de uso",p.optString("tipo_uso"));append(extra,"Usuário de destino",p.optString("usuario_destino_nome",p.optString("usuario_destino_id")));append(extra,"Motivo",p.optString("motivo_uso"));append(extra,"Previsão de devolução",p.optString("devolucao_prevista"));put(f,"observacao",extra.toString());JSONArray rs=p.optJSONArray("respostas");if(rs!=null)for(int i=0;i<rs.length();i++){JSONObject x=rs.optJSONObject(i);if(x!=null&&x.optInt("item_id")>0)f.put("item["+x.optInt("item_id")+"]",x.optString("resposta","ATENCAO"));}String sig=p.optString("assinatura_path_local","");Response r=multipart(ctx,"checklist_veiculo_salvar.php",f,photoFiles(photosJson,sig));ensureRedirectOk(r,"checklist");return new JSONObject().put("ok",true).put("mensagem","Checklist enviado para aprovação.");}
    private static JSONObject syncRoute(Context ctx,JSONObject p) throws Exception{JSONArray pts=p.optJSONArray("points");if(pts==null||pts.length()==0)throw new IllegalStateException("A rota não possui posições GPS salvas.");JSONObject first=pts.optJSONObject(0),last=pts.optJSONObject(pts.length()-1);Map<String,String> s=baseFields(ctx);s.put("action","start");put(s,"programacao_id",n(p.optInt("programacao_id")));put(s,"titulo",p.optString("title","Rota de campo"));put(s,"latitude",String.valueOf(first.optDouble("latitude")));put(s,"longitude",String.valueOf(first.optDouble("longitude")));JSONObject st=parseJson(request(ctx,"POST","rota_api.php",form(s).getBytes(StandardCharsets.UTF_8),"application/x-www-form-urlencoded; charset=utf-8",false,null).body);if(!st.optBoolean("ok",false))throw new IllegalStateException(st.optString("error","Não foi possível iniciar a rota no servidor."));int sid=st.optInt("session_id");for(int i=0;i<pts.length();i++){JSONObject x=pts.optJSONObject(i);if(x==null)continue;Map<String,String> g=baseFields(ctx);g.put("session_id",String.valueOf(sid));g.put("latitude",String.valueOf(x.optDouble("latitude")));g.put("longitude",String.valueOf(x.optDouble("longitude")));if(x.has("accuracy"))g.put("precisao",String.valueOf(x.optDouble("accuracy")));if(x.has("altitude"))g.put("altitude",String.valueOf(x.optDouble("altitude")));if(x.has("speed"))g.put("velocidade",String.valueOf(x.optDouble("speed")));if(x.has("bearing"))g.put("direcao",String.valueOf(x.optDouble("bearing")));g.put("timestamp",String.valueOf(parseTime(x.optString("captured_at"))));JSONObject gr=parseJson(request(ctx,"POST","gps.php",form(g).getBytes(StandardCharsets.UTF_8),"application/x-www-form-urlencoded; charset=utf-8",false,null).body);if(!gr.optBoolean("ok",false))throw new IllegalStateException(gr.optString("error","Falha ao enviar uma posição da rota."));}Map<String,String> e=baseFields(ctx);e.put("action","stop");e.put("session_id",String.valueOf(sid));e.put("latitude",String.valueOf(last.optDouble("latitude")));e.put("longitude",String.valueOf(last.optDouble("longitude")));JSONObject end=parseJson(request(ctx,"POST","rota_api.php",form(e).getBytes(StandardCharsets.UTF_8),"application/x-www-form-urlencoded; charset=utf-8",false,null).body);if(!end.optBoolean("ok",false))throw new IllegalStateException(end.optString("error","Falha ao finalizar a rota."));return end;}

    private static long parseTime(String s){try{return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).parse(s).getTime();}catch(Exception e){return System.currentTimeMillis();}}
    private static void append(StringBuilder b,String label,String value){if(value==null||value.trim().isEmpty()||"0".equals(value))return;if(b.length()>0)b.append("\n");b.append(label).append(": ").append(value);}
    private static List<FilePart> photoFiles(String photosJson,String signature){List<FilePart> out=new ArrayList<>();try{JSONArray a=new JSONArray(photosJson==null?"[]":photosJson);for(int i=0;i<a.length();i++){String p=a.opt(i) instanceof JSONObject?a.optJSONObject(i).optString("path"):a.optString(i);File f=new File(p);if(f.isFile())out.add(new FilePart("fotos[]",f));}}catch(Exception ignored){}if(signature!=null&&!signature.isEmpty()){File f=new File(signature);if(f.isFile())out.add(new FilePart("fotos[]",f));}return out;}
    private static JSONArray parseSelect(String html,String name,String label) throws Exception{JSONArray a=new JSONArray();Matcher sm=Pattern.compile("<select[^>]*name=[\"']"+Pattern.quote(name)+"[\"'][^>]*>(.*?)</select>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html);if(!sm.find())return a;Matcher om=OPTION.matcher(sm.group(1));while(om.find()){int id=Integer.parseInt(om.group(2));String text=clean(om.group(4));if(id<=0||text.isEmpty())continue;JSONObject o=new JSONObject();o.put("id",id);o.put(label,text);a.put(o);}return a;}
    private static JSONArray parseVehicles(String html) throws Exception{JSONArray src=parseSelect(html,"veiculo_id","placa"),out=new JSONArray();for(int i=0;i<src.length();i++){JSONObject x=src.getJSONObject(i);String txt=x.optString("placa");JSONObject o=new JSONObject();o.put("id",x.optInt("id"));o.put("placa",txt);o.put("modelo",txt);out.put(o);}return out;}
    private static JSONArray parseChecklistItems(String html) throws Exception{JSONArray a=new JSONArray();Pattern p=Pattern.compile("<div class=[\"']vc-row[\"']>.*?<b>(.*?)</b>.*?name=[\"']item\\[(\\d+)\\][\"']",Pattern.CASE_INSENSITIVE|Pattern.DOTALL);Matcher m=p.matcher(html);while(m.find()){JSONObject o=new JSONObject();String raw=m.group(1);boolean req=raw.contains("*");o.put("id",Integer.parseInt(m.group(2)));o.put("nome",clean(raw).replace("*","").trim());o.put("obrigatorio",req?1:0);a.put(o);}return a;}
    private static JSONObject getJson(Context ctx,String path) throws Exception{Response r=request(ctx,"GET",path,(byte[])null,null,false,null);JSONObject j=parseJson(r.body);if(!j.optBoolean("ok",false))throw new IllegalStateException(j.optString("error","Não foi possível baixar os dados."));return j;}
    private static JSONObject parseJson(String text) throws Exception{try{return new JSONObject(text);}catch(Exception e){throw new IllegalStateException("A plataforma retornou uma resposta inválida.");}}
    private static Map<String,String> baseFields(Context ctx){Map<String,String> f=new LinkedHashMap<>();f.put("csrf",OfflineDb.get(ctx).getSetting("web_csrf",""));return f;}
    private static void ensureRedirectOk(Response r,String what){String loc=r.location==null?"":r.location;if(loc.contains("erro="))throw new IllegalStateException("Não foi possível enviar "+what+".");if(r.code>=400)throw new IllegalStateException("Não foi possível enviar "+what+".");}
    private static void put(Map<String,String> m,String k,String v){if(v!=null&&!v.isEmpty()&&!"0".equals(v)&&!"NaN".equals(v))m.put(k,v);}
    private static String n(int x){return x>0?String.valueOf(x):"";}
    private static JSONObject json(String s){try{return new JSONObject(s);}catch(Exception e){return new JSONObject();}}
    private static JSONArray array(String s){try{return new JSONArray(s);}catch(Exception e){return new JSONArray();}}
    private static String dateOffset(int days){java.util.Calendar c=java.util.Calendar.getInstance();c.add(java.util.Calendar.DAY_OF_YEAR,days);return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(c.getTime());}
    private static String clean(String s){return s==null?"":s.replaceAll("<[^>]+>","").replace("&middot;","·").replace("&amp;","&").replace("&nbsp;"," ").replace("&#039;","'").replace("&quot;","\"").trim();}
    private static String extractCsrf(String html){Matcher m=CSRF.matcher(html==null?"":html);return m.find()?m.group(1):"";}
    private static String form(Map<String,String> fields) throws Exception{StringBuilder b=new StringBuilder();for(Map.Entry<String,String> e:fields.entrySet()){if(b.length()>0)b.append('&');b.append(URLEncoder.encode(e.getKey(),"UTF-8")).append('=').append(URLEncoder.encode(e.getValue()==null?"":e.getValue(),"UTF-8"));}return b.toString();}
    private static Response multipart(Context ctx,String path,Map<String,String> fields,List<FilePart> files) throws Exception{String boundary="----AgroDominium"+System.currentTimeMillis();ByteArrayOutputStream body=new ByteArrayOutputStream();for(Map.Entry<String,String> e:fields.entrySet())write(body,"--"+boundary+"\r\nContent-Disposition: form-data; name=\""+e.getKey()+"\"\r\n\r\n"+(e.getValue()==null?"":e.getValue())+"\r\n");for(FilePart fp:files){File f=fp.file;if(!f.isFile())continue;write(body,"--"+boundary+"\r\nContent-Disposition: form-data; name=\""+fp.field+"\"; filename=\""+f.getName()+"\"\r\nContent-Type: image/jpeg\r\n\r\n");try(FileInputStream in=new FileInputStream(f)){byte[] buf=new byte[32768];int n;while((n=in.read(buf))>0)body.write(buf,0,n);}write(body,"\r\n");}write(body,"--"+boundary+"--\r\n");return request(ctx,"POST",path,body.toByteArray(),"multipart/form-data; boundary="+boundary,false,null);}
    private static void write(ByteArrayOutputStream out,String s) throws Exception{out.write(s.getBytes(StandardCharsets.UTF_8));}
    private static Response request(Context ctx,String method,String path,byte[] body,String contentType,boolean follow,String accept) throws Exception{OfflineDb db=OfflineDb.get(ctx);HttpURLConnection c=(HttpURLConnection)new URL(ROOT+path).openConnection();c.setRequestMethod(method);c.setConnectTimeout(20000);c.setReadTimeout(90000);c.setInstanceFollowRedirects(follow);c.setRequestProperty("User-Agent","AgroDominium-Android/2.2");c.setRequestProperty("Accept",accept==null?"*/*":accept);String cookie=db.getSetting("web_cookie","");if(!cookie.isEmpty())c.setRequestProperty("Cookie",cookie);if(body!=null){c.setDoOutput(true);if(contentType!=null)c.setRequestProperty("Content-Type",contentType);c.setFixedLengthStreamingMode(body.length);try(OutputStream os=c.getOutputStream()){os.write(body);}}int code=c.getResponseCode();captureCookies(db,c);String loc=c.getHeaderField("Location");InputStream in=code>=400?c.getErrorStream():c.getInputStream();String text=read(in);c.disconnect();return new Response(code,text,loc);}
    private static void captureCookies(OfflineDb db,HttpURLConnection c){List<String> set=c.getHeaderFields().get("Set-Cookie");if(set==null)set=c.getHeaderFields().get("set-cookie");if(set==null)return;Map<String,String> jar=new LinkedHashMap<>();String old=db.getSetting("web_cookie","");for(String part:old.split(";")){int eq=part.indexOf('=');if(eq>0)jar.put(part.substring(0,eq).trim(),part.substring(eq+1).trim());}for(String h:set){if(h==null)continue;String first=h.split(";",2)[0];int eq=first.indexOf('=');if(eq>0)jar.put(first.substring(0,eq).trim(),first.substring(eq+1).trim());}StringBuilder out=new StringBuilder();for(Map.Entry<String,String> e:jar.entrySet()){if(out.length()>0)out.append("; ");out.append(e.getKey()).append('=').append(e.getValue());}db.putSetting("web_cookie",out.toString());}
    private static String read(InputStream in) throws Exception{if(in==null)return "";StringBuilder b=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null)b.append(line).append('\n');}return b.toString();}
    private static final class Response{final int code;final String body;final String location;Response(int c,String b,String l){code=c;body=b;location=l;}}
    private static final class FilePart{final String field;final File file;FilePart(String f,File x){field=f;file=x;}}
}
