package com.paf.gestaooperacional;

import android.content.Context;
import android.util.Base64;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.File;
import java.io.FileInputStream;
import java.util.Locale;

public class SyncEngine {
    public interface Progress { void onProgress(int done,int total,String message); }
    public static JSONObject refresh(Context ctx,int requestedGroup) throws Exception {OfflineDb db=OfflineDb.get(ctx);String token=db.getSetting("token","");if(token.isEmpty())throw new IllegalStateException("Faça login online pelo menos uma vez.");int gid=requestedGroup>0?requestedGroup:parseInt(db.getSetting("group_id","0"));if(gid<=0)gid=1;JSONObject j=ApiClient.bootstrap(token,gid);db.saveSnapshot(j.toString());db.putSetting("group_id",String.valueOf(j.optInt("group_id",gid)));if(j.has("user"))db.putSetting("user_json",j.getJSONObject("user").toString());if(j.has("groups"))db.putSetting("groups_json",j.getJSONArray("groups").toString());return j;}
    public static JSONObject syncAll(Context ctx,Progress progress,boolean refreshAfter) throws Exception {OfflineDb db=OfflineDb.get(ctx);db.resetSending();String token=db.getSetting("token","");if(token.isEmpty())throw new IllegalStateException("Sessão móvel não configurada.");if(!ApiClient.isOnline(ctx))throw new IllegalStateException("Sem internet. Os dados continuam salvos no aparelho.");JSONArray pending=db.pending(300);int total=pending.length(),done=0,failed=0;for(int i=0;i<pending.length();i++){JSONObject q=pending.getJSONObject(i);long id=q.getLong("id");db.markSending(id);String type=q.getString("type");try{JSONObject op=new JSONObject();op.put("client_uuid",q.getString("client_uuid"));op.put("type",type);op.put("group_id",q.optInt("group_id",parseInt(db.getSetting("group_id","0"))));JSONObject payload=new JSONObject(q.optString("payload_json","{}"));if("route.sync".equals(type)){String ru=payload.optString("route_uuid",q.getString("client_uuid"));payload=db.buildRoutePayload(ru);}op.put("payload",payload);op.put("photos",encodePhotos(q.optString("photos_json","[]")));JSONObject response=ApiClient.sync(token,op);db.markSynced(id,response.toString());if("route.sync".equals(type))db.markRouteSynced(payload.optString("route_uuid",q.getString("client_uuid")));done++;if(progress!=null)progress.onProgress(done,total,"Sincronizado: "+pretty(type));}catch(Exception e){failed++;db.markFailed(id,e.getMessage()==null?e.toString():e.getMessage());if(progress!=null)progress.onProgress(done,total,"Falha em "+pretty(type));if(e instanceof ApiClient.ApiException && ((ApiClient.ApiException)e).status==401)throw e;}}db.purgeSynced();JSONObject fresh=null;if(refreshAfter&&failed==0){try{fresh=refresh(ctx,parseInt(db.getSetting("group_id","0")));}catch(Exception ignored){}}JSONObject out=new JSONObject();out.put("ok",failed==0);out.put("synced",done);out.put("failed",failed);out.put("pending",db.pendingCount());if(fresh!=null)out.put("refreshed",true);return out;}
    private static JSONArray encodePhotos(String json) throws Exception {JSONArray src;try{src=new JSONArray(json);}catch(Exception e){src=new JSONArray();}JSONArray out=new JSONArray();for(int i=0;i<src.length();i++){String path;if(src.opt(i) instanceof JSONObject)path=src.getJSONObject(i).optString("path","");else path=src.optString(i,"");if(path.isEmpty())continue;File f=new File(path);if(!f.isFile())continue;byte[] b=readFile(f);JSONObject p=new JSONObject();p.put("name",f.getName());p.put("mime",mime(f.getName()));p.put("data",Base64.encodeToString(b,Base64.NO_WRAP));out.put(p);}return out;}
    private static byte[] readFile(File f) throws Exception {long len=f.length();if(len>12L*1024*1024)throw new IllegalStateException("Foto local maior que 12 MB: "+f.getName());byte[] b=new byte[(int)len];try(FileInputStream in=new FileInputStream(f)){int off=0,n;while(off<b.length&&(n=in.read(b,off,b.length-off))>0)off+=n;if(off!=b.length)throw new IllegalStateException("Falha ao ler foto local.");}return b;}
    private static String mime(String n){String x=n.toLowerCase(Locale.ROOT);if(x.endsWith(".png"))return "image/png";if(x.endsWith(".webp"))return "image/webp";if(x.endsWith(".heic"))return "image/heic";return "image/jpeg";}
    private static String pretty(String type){return type.replace("programacao.create","programação").replace("ponto.create","ponto").replace("route.sync","rota").replace("vehicle_checklist.create","checklist do veículo");}
    private static int parseInt(String s){try{return Integer.parseInt(s);}catch(Exception e){return 0;}}
}
